// Generated by gencpp from file myPkg/comp.msg
// DO NOT EDIT!


#ifndef MYPKG_MESSAGE_COMP_H
#define MYPKG_MESSAGE_COMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myPkg
{
template <class ContainerAllocator>
struct comp_
{
  typedef comp_<ContainerAllocator> Type;

  comp_()
    : real(0)
    , imaginary(0)  {
    }
  comp_(const ContainerAllocator& _alloc)
    : real(0)
    , imaginary(0)  {
  (void)_alloc;
    }



   typedef int32_t _real_type;
  _real_type real;

   typedef int32_t _imaginary_type;
  _imaginary_type imaginary;





  typedef boost::shared_ptr< ::myPkg::comp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myPkg::comp_<ContainerAllocator> const> ConstPtr;

}; // struct comp_

typedef ::myPkg::comp_<std::allocator<void> > comp;

typedef boost::shared_ptr< ::myPkg::comp > compPtr;
typedef boost::shared_ptr< ::myPkg::comp const> compConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myPkg::comp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myPkg::comp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myPkg::comp_<ContainerAllocator1> & lhs, const ::myPkg::comp_<ContainerAllocator2> & rhs)
{
  return lhs.real == rhs.real &&
    lhs.imaginary == rhs.imaginary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myPkg::comp_<ContainerAllocator1> & lhs, const ::myPkg::comp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myPkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::myPkg::comp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myPkg::comp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPkg::comp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPkg::comp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPkg::comp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPkg::comp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myPkg::comp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29494601c99dbe58165af75a7e636359";
  }

  static const char* value(const ::myPkg::comp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29494601c99dbe58ULL;
  static const uint64_t static_value2 = 0x165af75a7e636359ULL;
};

template<class ContainerAllocator>
struct DataType< ::myPkg::comp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myPkg/comp";
  }

  static const char* value(const ::myPkg::comp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myPkg::comp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 real \n"
"int32 imaginary \n"
;
  }

  static const char* value(const ::myPkg::comp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myPkg::comp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.real);
      stream.next(m.imaginary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct comp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myPkg::comp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myPkg::comp_<ContainerAllocator>& v)
  {
    s << indent << "real: ";
    Printer<int32_t>::stream(s, indent + "  ", v.real);
    s << indent << "imaginary: ";
    Printer<int32_t>::stream(s, indent + "  ", v.imaginary);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPKG_MESSAGE_COMP_H
