// Generated by gencpp from file myPkg/counterResponse.msg
// DO NOT EDIT!


#ifndef MYPKG_MESSAGE_COUNTERRESPONSE_H
#define MYPKG_MESSAGE_COUNTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myPkg
{
template <class ContainerAllocator>
struct counterResponse_
{
  typedef counterResponse_<ContainerAllocator> Type;

  counterResponse_()
    : count(0)  {
    }
  counterResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::myPkg::counterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myPkg::counterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct counterResponse_

typedef ::myPkg::counterResponse_<std::allocator<void> > counterResponse;

typedef boost::shared_ptr< ::myPkg::counterResponse > counterResponsePtr;
typedef boost::shared_ptr< ::myPkg::counterResponse const> counterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myPkg::counterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myPkg::counterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myPkg::counterResponse_<ContainerAllocator1> & lhs, const ::myPkg::counterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myPkg::counterResponse_<ContainerAllocator1> & lhs, const ::myPkg::counterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myPkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::myPkg::counterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myPkg::counterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPkg::counterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPkg::counterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPkg::counterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPkg::counterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myPkg::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::myPkg::counterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::myPkg::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myPkg/counterResponse";
  }

  static const char* value(const ::myPkg::counterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myPkg::counterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 count\n"
"\n"
;
  }

  static const char* value(const ::myPkg::counterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myPkg::counterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct counterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myPkg::counterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myPkg::counterResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPKG_MESSAGE_COUNTERRESPONSE_H
