// Generated by gencpp from file myPkg/wordcount.msg
// DO NOT EDIT!


#ifndef MYPKG_MESSAGE_WORDCOUNT_H
#define MYPKG_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <myPkg/wordcountRequest.h>
#include <myPkg/wordcountResponse.h>


namespace myPkg
{

struct wordcount
{

typedef wordcountRequest Request;
typedef wordcountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wordcount
} // namespace myPkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myPkg::wordcount > {
  static const char* value()
  {
    return "fcbde222c0a68b4a1d0b96c95b82d17a";
  }

  static const char* value(const ::myPkg::wordcount&) { return value(); }
};

template<>
struct DataType< ::myPkg::wordcount > {
  static const char* value()
  {
    return "myPkg/wordcount";
  }

  static const char* value(const ::myPkg::wordcount&) { return value(); }
};


// service_traits::MD5Sum< ::myPkg::wordcountRequest> should match
// service_traits::MD5Sum< ::myPkg::wordcount >
template<>
struct MD5Sum< ::myPkg::wordcountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myPkg::wordcount >::value();
  }
  static const char* value(const ::myPkg::wordcountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPkg::wordcountRequest> should match
// service_traits::DataType< ::myPkg::wordcount >
template<>
struct DataType< ::myPkg::wordcountRequest>
{
  static const char* value()
  {
    return DataType< ::myPkg::wordcount >::value();
  }
  static const char* value(const ::myPkg::wordcountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myPkg::wordcountResponse> should match
// service_traits::MD5Sum< ::myPkg::wordcount >
template<>
struct MD5Sum< ::myPkg::wordcountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myPkg::wordcount >::value();
  }
  static const char* value(const ::myPkg::wordcountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPkg::wordcountResponse> should match
// service_traits::DataType< ::myPkg::wordcount >
template<>
struct DataType< ::myPkg::wordcountResponse>
{
  static const char* value()
  {
    return DataType< ::myPkg::wordcount >::value();
  }
  static const char* value(const ::myPkg::wordcountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPKG_MESSAGE_WORDCOUNT_H
